name: Deploy vuepress website
on:
  # push:
  #   branches:
  #     - master
  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          TARGET_REPO: merfais/vue-grid-layout-v3
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: cd website && yarn && yarn build
          BUILD_DIR: public
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
